#pragma once

#include "Core/TypeDef.h"

NAMESPACE_BEGIN

enum PHYSICS_SHAPE_TYPE
{
	PHYSICS_SHAPE_TYPE_SPHERE,
	PHYSICS_SHAPE_TYPE_CAPSULE,
	PHYSICS_SHAPE_TYPE_BOX,
	PHYSICS_SHAPE_TYPE_PLANE,
	PHYSICS_SHAPE_TYPE_CONVEX_MESH,
	PHYSICS_SHAPE_TYPE_TRIANGLE_MESH,
};

NAMESPACE_END