#pragma once

#include "TypeDef.h"

#include "Modules/Graphics/GraphicsFundamental.h"

NAMESPACE_DX12_BEGIN

namespace dx12utils
{

inline DXGI_FORMAT ConvertToDX12DepthBufferFormat(GRAPHICS_DATA_FORMAT::FORMAT format)
{
	static DXGI_FORMAT MAPPING[GRAPHICS_DATA_FORMAT::COUNT + 1] = {};

	if (MAPPING[GRAPHICS_DATA_FORMAT::COUNT] == 0)
	{
		MAPPING[GRAPHICS_DATA_FORMAT::FORMAT_R32_FLOAT] = DXGI_FORMAT::DXGI_FORMAT_D32_FLOAT;
		MAPPING[GRAPHICS_DATA_FORMAT::FORMAT_R32G32_FLOAT] = DXGI_FORMAT::DXGI_FORMAT_D24_UNORM_S8_UINT;
		MAPPING[GRAPHICS_DATA_FORMAT::FORMAT_R32G32B32_FLOAT] = DXGI_FORMAT::DXGI_FORMAT_D24_UNORM_S8_UINT;
		MAPPING[GRAPHICS_DATA_FORMAT::FORMAT_R32G32B32A32_FLOAT] = DXGI_FORMAT::DXGI_FORMAT_D24_UNORM_S8_UINT;

		MAPPING[GRAPHICS_DATA_FORMAT::FORMAT_R8_UNORM] = DXGI_FORMAT::DXGI_FORMAT_D24_UNORM_S8_UINT;
		MAPPING[GRAPHICS_DATA_FORMAT::FORMAT_R8G8B8_UNORM] = DXGI_FORMAT::DXGI_FORMAT_D24_UNORM_S8_UINT;
		MAPPING[GRAPHICS_DATA_FORMAT::FORMAT_R8G8B8A8_UNORM] = DXGI_FORMAT::DXGI_FORMAT_D24_UNORM_S8_UINT;

		MAPPING[GRAPHICS_DATA_FORMAT::UNKNOWN] = DXGI_FORMAT::DXGI_FORMAT_UNKNOWN;

		MAPPING[GRAPHICS_DATA_FORMAT::COUNT] = DXGI_FORMAT::DXGI_FORMAT_FORCE_UINT;
	}

	return MAPPING[format];
}

inline DXGI_FORMAT ConvertToDX12Format(GRAPHICS_DATA_FORMAT::FORMAT format)
{
	static DXGI_FORMAT MAPPING[GRAPHICS_DATA_FORMAT::COUNT + 1] = {};

	if (MAPPING[GRAPHICS_DATA_FORMAT::COUNT] == 0)
	{
		MAPPING[GRAPHICS_DATA_FORMAT::FORMAT_R32_FLOAT] = DXGI_FORMAT::DXGI_FORMAT_R32_FLOAT;
		MAPPING[GRAPHICS_DATA_FORMAT::FORMAT_R32G32_FLOAT] = DXGI_FORMAT::DXGI_FORMAT_R32G32_FLOAT;
		MAPPING[GRAPHICS_DATA_FORMAT::FORMAT_R32G32B32_FLOAT] = DXGI_FORMAT::DXGI_FORMAT_R32G32B32_FLOAT;
		MAPPING[GRAPHICS_DATA_FORMAT::FORMAT_R32G32B32A32_FLOAT] = DXGI_FORMAT::DXGI_FORMAT_R32G32B32A32_FLOAT;

		MAPPING[GRAPHICS_DATA_FORMAT::FORMAT_R16G16B16A16_UINT] = DXGI_FORMAT::DXGI_FORMAT_R16G16B16A16_UINT;

		MAPPING[GRAPHICS_DATA_FORMAT::FORMAT_R8_UNORM] = DXGI_FORMAT::DXGI_FORMAT_R8_UNORM;
		MAPPING[GRAPHICS_DATA_FORMAT::FORMAT_R8G8B8_UNORM] = DXGI_FORMAT::DXGI_FORMAT_R8G8B8A8_UNORM;
		MAPPING[GRAPHICS_DATA_FORMAT::FORMAT_R8G8B8A8_UNORM] = DXGI_FORMAT::DXGI_FORMAT_R8G8B8A8_UNORM;

		MAPPING[GRAPHICS_DATA_FORMAT::UNKNOWN] = DXGI_FORMAT::DXGI_FORMAT_UNKNOWN;

		MAPPING[GRAPHICS_DATA_FORMAT::COUNT] = DXGI_FORMAT::DXGI_FORMAT_FORCE_UINT;
	}

	return MAPPING[format];
}

inline D3D12_PRIMITIVE_TOPOLOGY_TYPE ConvertToDX12PrimitiveTopoplogy(GRAPHICS_PRIMITIVE_TOPOLOGY::TYPE type)
{
	static D3D12_PRIMITIVE_TOPOLOGY_TYPE MAPPING[GRAPHICS_PRIMITIVE_TOPOLOGY::COUNT + 1] = {};

	if (MAPPING[GRAPHICS_PRIMITIVE_TOPOLOGY::COUNT] == 0)
	{
		MAPPING[GRAPHICS_PRIMITIVE_TOPOLOGY::PRIMITIVE_TOPOLOGY_TYPE_LINE] = D3D12_PRIMITIVE_TOPOLOGY_TYPE::D3D12_PRIMITIVE_TOPOLOGY_TYPE_LINE;
		MAPPING[GRAPHICS_PRIMITIVE_TOPOLOGY::PRIMITIVE_TOPOLOGY_TYPE_PATCH] = D3D12_PRIMITIVE_TOPOLOGY_TYPE::D3D12_PRIMITIVE_TOPOLOGY_TYPE_PATCH;
		MAPPING[GRAPHICS_PRIMITIVE_TOPOLOGY::PRIMITIVE_TOPOLOGY_TYPE_POINT] = D3D12_PRIMITIVE_TOPOLOGY_TYPE::D3D12_PRIMITIVE_TOPOLOGY_TYPE_POINT;
		MAPPING[GRAPHICS_PRIMITIVE_TOPOLOGY::PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE] = D3D12_PRIMITIVE_TOPOLOGY_TYPE::D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;
		MAPPING[GRAPHICS_PRIMITIVE_TOPOLOGY::PRIMITIVE_TOPOLOGY_TYPE_UNDEFINED] = D3D12_PRIMITIVE_TOPOLOGY_TYPE::D3D12_PRIMITIVE_TOPOLOGY_TYPE_UNDEFINED;

		MAPPING[GRAPHICS_PRIMITIVE_TOPOLOGY::COUNT] = (D3D12_PRIMITIVE_TOPOLOGY_TYPE)10;
	}

	return MAPPING[type];
}

inline D3D12_PRIMITIVE_TOPOLOGY ConvertToD3DPrimitiveTopoplogy(D3D12_PRIMITIVE_TOPOLOGY_TYPE type)
{
	static D3D12_PRIMITIVE_TOPOLOGY MAPPING[10] = {};

	if (MAPPING[9] == 0)
	{
		MAPPING[D3D12_PRIMITIVE_TOPOLOGY_TYPE::D3D12_PRIMITIVE_TOPOLOGY_TYPE_LINE] = D3D12_PRIMITIVE_TOPOLOGY::D3D_PRIMITIVE_TOPOLOGY_LINELIST;
		MAPPING[D3D12_PRIMITIVE_TOPOLOGY_TYPE::D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE] = D3D12_PRIMITIVE_TOPOLOGY::D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST;

		MAPPING[9] = (D3D12_PRIMITIVE_TOPOLOGY)1;
	}

	return MAPPING[type];
}

inline D3D12_INPUT_ELEMENT_DESC ConvertToDX12InputElement(const GRAPHICS_PIPELINE_INPUT_ELEMENT_DESC& desc)
{
	D3D12_INPUT_ELEMENT_DESC ret = {};

	ret.AlignedByteOffset = desc.alignedByteOffset;
	ret.Format = ConvertToDX12Format(desc.format);
	ret.InputSlot = desc.inputSlot;
	ret.InputSlotClass = (D3D12_INPUT_CLASSIFICATION)desc.inputSlotClass;
	ret.InstanceDataStepRate = desc.instanceDataStepRate;
	ret.SemanticIndex = desc.semanticIndex;
	ret.SemanticName = desc.semanticName;

	return ret;
}

inline D3D12_CULL_MODE ConvertToDX12CullMode(GRAPHICS_CULL_MODE::MODE mode)
{
	static D3D12_CULL_MODE MAPPING[GRAPHICS_CULL_MODE::MODE::COUNT + 1] = {};

	if (MAPPING[GRAPHICS_CULL_MODE::MODE::COUNT] == 0)
	{
		MAPPING[GRAPHICS_CULL_MODE::BACK] = D3D12_CULL_MODE::D3D12_CULL_MODE_BACK;
		MAPPING[GRAPHICS_CULL_MODE::FRONT] = D3D12_CULL_MODE::D3D12_CULL_MODE_FRONT;
		MAPPING[GRAPHICS_CULL_MODE::NONE] = D3D12_CULL_MODE::D3D12_CULL_MODE_NONE;

		MAPPING[GRAPHICS_CULL_MODE::MODE::COUNT] = (D3D12_CULL_MODE)1;
	}

	return MAPPING[mode];
}

inline D3D12_FILL_MODE ConvertToDX12FillMode(GRAPHICS_FILL_MODE::MODE mode)
{
	static D3D12_FILL_MODE MAPPING[GRAPHICS_FILL_MODE::MODE::COUNT + 1] = {};

	if (MAPPING[GRAPHICS_FILL_MODE::MODE::COUNT] == 0)
	{
		MAPPING[GRAPHICS_FILL_MODE::SOLID] = D3D12_FILL_MODE_SOLID;
		MAPPING[GRAPHICS_FILL_MODE::WIREFRAME] = D3D12_FILL_MODE_WIREFRAME;

		MAPPING[GRAPHICS_FILL_MODE::MODE::COUNT] = (D3D12_FILL_MODE)1;
	}

	return MAPPING[mode];
}

}

NAMESPACE_DX12_END